from io import BytesIO
from zipfile import ZipFile,ZIP_DEFLATED
from html import escape
import re

def esc(x): return escape(str(x or ''))
def make_html(plan,req):
 color=req.get('primary_color') or '#6C4CFF'; name=esc(plan.get('title','Webify Site')); hero_title=esc(plan.get('hero_title','Your new website')); hero_sub=esc(plan.get('hero_subtitle','')); cta=esc(plan.get('cta','Get Started'))
 chunks=[]
 for s in plan.get('sections',[]):
  sid=re.sub(r'[^a-z0-9]+','-',str(s.get('title','section')).lower()).strip('-')
  cards=''.join(f'<article class="card"><h3>{esc(i.get("title"))}</h3><p>{esc(i.get("text"))}</p><small>{esc(i.get("meta"))}</small></article>' for i in s.get('items',[]))
  chunks.append(f'<section class="section" id="{sid}"><div class="container"><span class="eyebrow">WEBIFY</span><h2>{esc(s.get("title"))}</h2><p class="lead">{esc(s.get("intro"))}</p><div class="grid">{cards}</div></div></section>')
 nav=''.join(f'<a href="#{re.sub(r"[^a-z0-9]+","-",str(x).lower()).strip("-")}">{esc(x)}</a>' for x in plan.get('nav',[])[1:])
 return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(plan.get("seo_title",name))}</title><meta name="description" content="{esc(plan.get("seo_description",plan.get("summary","")))}"><meta name="keywords" content="{esc(", ".join(plan.get("keywords",[])))}"><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Space+Grotesk:wght@500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="style.css"></head><body style="--brand:{color}"><header class="site-header"><div class="container nav"><a class="logo" href="#home">{name}</a><button class="menu" aria-label="Open navigation" onclick="toggleMenu()">☰</button><nav id="nav"><a href="#home">Home</a>{nav}</nav></div></header><main><section class="hero" id="home"><div class="container hero-inner"><span class="pill">✦ BUILT WITH WEBIFY</span><h1>{hero_title}</h1><p>{hero_sub}</p><a class="btn" href="#contact">{cta} <span>→</span></a></div></section>{''.join(chunks)}<section class="section" id="contact"><div class="container contact"><div><span class="eyebrow">CONTACT</span><h2>Ready to start?</h2><p>{esc(req.get('business_description','Tell us what you need and we will be in touch.'))}</p><p class="contact-details">{esc(req.get('contact',''))}</p></div><form onsubmit="submitDemo(event)"><input required placeholder="Your name"><input required type="email" placeholder="Email address"><textarea required placeholder="How can we help?"></textarea><button class="btn" type="submit">{cta}</button><div id="form-message"></div></form></div></section></main><footer><div class="container footer"><span>© <span id="year"></span> {name}</span><span>{esc(req.get('footer_note','Built with Webify.'))}</span></div></footer><script src="script.js"></script></body></html>'''

def make_css(): return '''*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#fbfbfc;color:#111216;font-family:"DM Sans",sans-serif}a{text-decoration:none;color:inherit}.container{width:min(1160px,92%);margin:auto}.site-header{position:sticky;top:0;z-index:20;background:#fbfbfce6;backdrop-filter:blur(18px);border-bottom:1px solid #e8e8ec}.nav{height:76px;display:flex;align-items:center;justify-content:space-between}.logo{font:700 1.2rem "Space Grotesk"}.nav nav{display:flex;gap:26px;color:#666a73;font-weight:600}.nav nav a:hover{color:var(--brand)}.menu{display:none;border:0;background:none;font-size:1.5rem}.hero{min-height:650px;display:grid;place-items:center;background:radial-gradient(circle at 80% 15%,#6c4cff38,transparent 32%),linear-gradient(135deg,#101114,#201d29);color:#fff}.hero-inner{text-align:center;padding:90px 0}.pill,.eyebrow{font-size:.78rem;font-weight:800;letter-spacing:.14em;color:var(--brand)}.pill{display:inline-block;border:1px solid #ffffff2b;padding:8px 13px;border-radius:999px;color:#ddd}.hero h1{font:700 clamp(3rem,8vw,6.8rem)/.96 "Space Grotesk";letter-spacing:-.065em;max-width:980px;margin:24px auto}.hero p{max-width:760px;margin:0 auto 30px;color:#c7c7ce;font-size:1.18rem;line-height:1.75}.btn{display:inline-flex;gap:12px;align-items:center;justify-content:center;background:var(--brand);color:white;border:0;padding:14px 20px;border-radius:12px;font-weight:800;cursor:pointer}.section{padding:110px 0;border-bottom:1px solid #e9e9ed}.section h2{font:700 clamp(2.1rem,4vw,4rem)/1.05 "Space Grotesk";letter-spacing:-.05em;max-width:760px;margin:12px 0 18px}.lead{color:#696d76;max-width:760px;line-height:1.8;font-size:1.05rem}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:38px}.card{background:#fff;border:1px solid #e7e7eb;border-radius:20px;padding:28px;min-height:190px;box-shadow:0 10px 40px #15151a08}.card h3{font:700 1.25rem "Space Grotesk"}.card p{color:#70737b;line-height:1.7}.card small{color:var(--brand);font-weight:700}.contact{display:grid;grid-template-columns:1fr 1fr;gap:70px;align-items:start}.contact form{display:grid;gap:12px}.contact input,.contact textarea{width:100%;padding:15px;border:1px solid #dddde3;border-radius:12px;background:white;font:inherit}.contact textarea{min-height:150px;resize:vertical}.contact-details{white-space:pre-line;color:#676b73}footer{padding:28px 0}.footer{display:flex;justify-content:space-between;gap:20px;color:#7a7d84;font-size:.9rem}@media(max-width:760px){.nav nav{display:none;position:absolute;top:76px;left:0;right:0;background:#fff;padding:20px;flex-direction:column;border-bottom:1px solid #eee}.nav nav.open{display:flex}.menu{display:block}.grid,.contact{grid-template-columns:1fr}.section{padding:75px 0}.footer{flex-direction:column}}'''

def build_website_zip(plan,req):
 html=make_html(plan,req); memory=BytesIO()
 with ZipFile(memory,'w',ZIP_DEFLATED) as z:
  z.writestr('index.html',html); z.writestr('style.css',make_css()); z.writestr('script.js','function submitDemo(e){e.preventDefault();document.getElementById("form-message").textContent="Thanks! Your message has been captured in this demo."}function toggleMenu(){document.getElementById("nav").classList.toggle("open")}document.getElementById("year").textContent=new Date().getFullYear();'); z.writestr('README.md','# Website generated by Webify\n\nOpen index.html to preview the site.\n')
 return {'title':plan.get('title','Webify Website'),'summary':plan.get('summary',''),'slug':plan.get('slug') or 'webify-site','html':html,'zip_bytes':memory.getvalue(),'files':['index.html','style.css','script.js','README.md']}
